on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

 
      - uses: actions/checkout@v3
      - name: 'login to docker hub'
        run: docker login --username rawan123 --password dckr_pat_dQV3BXIhT0jHnOHcupF6vVJray0

        


